CREATE DATABASE QLTM1
GO
CREATE TABLE KHACHHANG (
	IDKH INT PRIMARY KEY,
	IDTK INT NOT NULL,
	TEN VARCHAR(10) NOT NULL,
	TENDEM VARCHAR(10) ,
	HO VARCHAR(10) ,
	NGAYSINH DATETIME ,
	DIACHI VARCHAR(100) NOT NULL,
	SDT VARCHAR(12) NOT NULL,
	AVATAR VARCHAR(12),
	EMAIL VARCHAR(12)
)
CREATE TABLE TAIKHOAN(
	IDTK INT PRIMARY KEY,
	TENDN VARCHAR(100) NOT NULL,
	PASS VARCHAR(100) NOT NULL
)
CREATE TABLE SANPHAM (
	IDSP INT PRIMARY KEY,
	IDLSP INT NOT NULL,
	TENSP VARCHAR(100) NOT NULL,
	SOLUONG INT NOT NULL,
	IMG VARCHAR(100),
	MOTA VARCHAR(100),
	GIABAN MONEY
)
CREATE TABLE BINHLUAN(
	IDBL INT PRIMARY KEY,
	IDKH INT NOT NULL,
	IDSP INT NOT NULL,
	NOIDUNGBL VARCHAR(50) NOT NULL
)
CREATE TABLE LOAISP (
	IDLSP INT PRIMARY KEY,
	TENLSP VARCHAR(50) NOT NULL
)
CREATE TABLE HOADON (
	IDHD INT PRIMARY KEY,
	IDKH INT NOT NULL,
	NGAYDATHANG DATETIME NOT NULL,
	NGAYGIAOHANG DATETIME,
	NOIGIAOHANG VARCHAR(100) NOT NULL,
	DAGIAO BIT NOT NULL
)
CREATE TABLE GIOHANG(
	IDKH INT NOT NULL,
	IDSP INT NOT NULL,
	SOLUONG INT NOT NULL,
	DADATMUA BIT NOT NULL,
	PRIMARY KEY(IDKH,IDSP)
)
CREATE TABLE CTHD (
	IDHD INT NOT NULL,
	IDSP INT NOT NULL,
	SOLUONG INT NOT NULL,
	PRIMARY KEY(IDHD,IDSP)
)
ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KH FOREIGN KEY (IDTK) REFERENCES TAIKHOAN(IDTK)
ALTER TABLE BINHLUAN
ADD CONSTRAINT FK_BL FOREIGN KEY (IDKH) REFERENCES KHACHHANG(IDKH)
ALTER TABLE BINHLUAN
ADD CONSTRAINT FK_BL1 FOREIGN KEY (IDSP) REFERENCES SANPHAM(IDSP)
ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SP FOREIGN KEY (IDLSP) REFERENCES LOAISP(IDLSP)
ALTER TABLE HOADON
ADD CONSTRAINT FK_HD FOREIGN KEY (IDKH) REFERENCES KHACHHANG(IDKH)
ALTER TABLE GIOHANG
ADD CONSTRAINT FK_GH FOREIGN KEY (IDKH) REFERENCES KHACHHANG(IDKH)
ALTER TABLE GIOHANG
ADD CONSTRAINT FK_GH1 FOREIGN KEY (IDSP) REFERENCES SANPHAM(IDSP)
ALTER TABLE CTHD
ADD CONSTRAINT FK_CT FOREIGN KEY (IDHD) REFERENCES HOADON(IDHD)
ALTER TABLE CTHD
ADD CONSTRAINT FK_CT1 FOREIGN KEY (IDSP) REFERENCES SANPHAM(IDSP)